/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaExportaModelo.java
 *
 * Created on 22/11/2009, 14:15:07
 */
package appcmmi.form.especificacao;

import appcmmi.db.facade.modelo.MaturidadeFacade;
import appcmmi.db.pojo.modelo.Maturidade;
import appcmmi.funcoes.Funcoes;
import appcmmi.funcoes.Propriedades;
import java.io.File;
import java.util.List;

/**
 *
 * @author diego
 */
public class TelaExportaModelo extends javax.swing.JFrame {

    /** Creates new form TelaExportaModelo */
    public TelaExportaModelo() {
        initComponents();
        String modelo = Propriedades.getPreferences().get(Propriedades.MODELO, "");
        if (!modelo.isEmpty()) {
            exportaModelo.setSelectedFile(new File(modelo));
        }
        exportaModelo.setApproveButtonText("Exportar");

        setVisible(true);
        setTitle("Exportar Modelo CMMI");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exportaModelo = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        exportaModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportaModeloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exportaModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exportaModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exportaModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportaModeloActionPerformed
        if (!evt.getActionCommand().equals("CancelSelection")) {
            try {
                List<Maturidade> lista = new MaturidadeFacade().exportaMaturidades();
                Funcoes.exportarArquivo(lista, exportaModelo.getSelectedFile().getAbsolutePath(), null);
                Funcoes.info("Modelo CMMI", "Modelo CMMI exportado com sucesso.");
                this.dispose();
            } catch (Exception ex) {
                Funcoes.erro("Erro", ex.getMessage());
            }

        }
    }//GEN-LAST:event_exportaModeloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new TelaExportaModelo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser exportaModelo;
    // End of variables declaration//GEN-END:variables
}
