/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaImprimir.java
 *
 * Created on 07/12/2009, 16:04:14
 */

package appcmmi.form.report;

import java.io.File;

/**
 *
 * @author diego
 */
public class TelaImprimir extends javax.swing.JDialog {

    /** Creates new form TelaImprimir */
    public TelaImprimir(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salvarem = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        salvarem.setApproveButtonText("Salvar");
        salvarem.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        salvarem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvaremActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salvarem, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salvarem, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvaremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvaremActionPerformed
        if (!evt.getActionCommand().equals("CancelSelection")) {
            file = salvarem.getSelectedFile();
        }
            this.dispose();
        
    }//GEN-LAST:event_salvaremActionPerformed

    public File getFile() {
        return file;
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                TelaImprimir dialog = new TelaImprimir(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser salvarem;
    // End of variables declaration//GEN-END:variables
    private File file;
}
