/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJInternalFrame.java
 *
 * Created on 03/12/2009, 13:06:53
 */
package appcmmi.form.report;

import appcmmi.db.facade.avaliacao.AvaliacaoFacade;
import appcmmi.db.pojo.avaliacao.Avaliacao;
import appcmmi.funcoes.Funcoes;
import appcmmi.funcoes.GerarRelatorio;
import java.io.File;
import java.util.Collection;

/**
 *
 * @author diego
 */
public class TelaReport extends javax.swing.JInternalFrame {

    public static int GERAL = 0;
    public static int RELATORIO = 1;

    /** Creates new form NewJInternalFrame */
    public TelaReport(int tipo) {
        initComponents();
        setVisible(true);
        this.tipo = tipo;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exportar = new javax.swing.JFileChooser();

        exportar.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exportar, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exportar, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public File getFile() {
        return file;
    }

    private void exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarActionPerformed
        if (!evt.getActionCommand().equals("CancelSelection")) {
            try {
                if (tipo == GERAL) {
                    Collection<Avaliacao> lista = new AvaliacaoFacade().pesquisaAvaliacao(null, null, null, null, null, null);
                    new GerarRelatorio().jasperReport(exportar.getSelectedFile(), "Avaliacoes", lista);
                    this.dispose();
                } else if (tipo == RELATORIO) {
                    file = exportar.getCurrentDirectory();
                }
            } catch (Exception ex) {
                ex.printStackTrace();
                Funcoes.erro("Relatório", ex.getMessage());
            }
        } else {
            dispose();
        }
    }//GEN-LAST:event_exportarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser exportar;
    // End of variables declaration//GEN-END:variables
    private int tipo;
    private File file;
}
