/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaEmpresa.java
 *
 * Created on 29/08/2009, 21:11:12
 */
package appcmmi.form.empresa;

import appcmmi.db.facade.EmpresaFacade;
import appcmmi.db.pojo.Empresa;
import appcmmi.db.pojo.Ativo;
import appcmmi.funcoes.Funcoes;
import appcmmi.modelo.bind.ModeloEmpresa;
import java.math.BigInteger;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;

/**
 *
 * @author Alexandre
 */
public class TelaEmpresa extends javax.swing.JInternalFrame {

    /** Creates new form TelaEmpresa */
    public TelaEmpresa() {
        try {
            empresas = new ModeloEmpresa();
            inicial();
        } catch (Exception ex) {
            Funcoes.erro("Erro", ex.getMessage());
        }
    }

    public TelaEmpresa(JDialog dialog) {
        this.depende = true;
        this.dialog = dialog;
        try {
            empresas = new ModeloEmpresa();
            inicial();
        } catch (Exception ex) {
            Funcoes.erro("Erro", ex.getMessage());
        }
    }

    private void habilita() {
        idEmpresa.setEnabled(true);
        salvar.setEnabled(false);
        cancelar.setEnabled(false);
        pesquisar.setEnabled(true);
        tabelaEmpresas.revalidate();
        tabelaEmpresas.repaint();
        alterar.setEnabled(true);
        tabelaEmpresas.setEnabled(true);
        empresas.setEditar(false);
    }

    private void inicial() throws ParseException {

        //MaskFormatter mf = new MaskFormatter("#####-####/#####-##");
        initComponents();
        //mf.install(cnpj);
        setClosable(!depende);
        selecionar.setVisible(depende);
        setMaximizable(false);
        setSize(730, 550);
        setTitle("Cadastro/Manutenção de Empresa");
        setVisible(true);
        cancelar.setEnabled(false);
        salvar.setEnabled(false);
        alterar.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idEmpresa = new javax.swing.JTextField();
        razaoSocial = new javax.swing.JTextField();
        complemento = new javax.swing.JTextField();
        endereco = new javax.swing.JTextField();
        novo = new javax.swing.JButton();
        insEstadual = new javax.swing.JTextField();
        sair = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        salvar = new javax.swing.JButton();
        pesquisar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        fantasia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        telefone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        contato = new javax.swing.JTextField();
        labelPatr = new javax.swing.JLabel();
        patrocinador = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEmpresas = new javax.swing.JTable();
        selecionar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        excluir = new javax.swing.JButton();
        cnpj = new javax.swing.JFormattedTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(true);
        setTitle("Cadastro de uma nova Empresa");
        getContentPane().setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Código:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 70, 17);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Razão Social:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 40, 90, 17);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Fantasia:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 40, 60, 17);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("CNPJ:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(9, 70, 80, 17);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Complemento:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(480, 100, 100, 17);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.empresa.idempresa}"), idEmpresa, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${not empty empresas.empresa.idempresa}"), idEmpresa, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        getContentPane().add(idEmpresa);
        idEmpresa.setBounds(90, 10, 130, 27);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.empresa.razaosocial}"), razaoSocial, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.editar}"), razaoSocial, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);

        getContentPane().add(razaoSocial);
        razaoSocial.setBounds(90, 40, 260, 27);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.empresa.complemento}"), complemento, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.editar}"), complemento, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);

        getContentPane().add(complemento);
        complemento.setBounds(580, 100, 80, 27);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.empresa.endereco}"), endereco, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.editar}"), endereco, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);

        getContentPane().add(endereco);
        endereco.setBounds(90, 100, 260, 20);

        novo.setText("Novo");
        novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoActionPerformed(evt);
            }
        });
        getContentPane().add(novo);
        novo.setBounds(240, 10, 80, 29);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.empresa.inscricaoestadual}"), insEstadual, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.editar}"), insEstadual, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);

        getContentPane().add(insEstadual);
        insEstadual.setBounds(410, 70, 250, 27);

        sair.setText("Fechar");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair);
        sair.setBounds(610, 430, 90, 29);

        alterar.setText("Alterar");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });
        getContentPane().add(alterar);
        alterar.setBounds(580, 190, 80, 29);

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        getContentPane().add(salvar);
        salvar.setBounds(400, 190, 80, 29);

        pesquisar.setText("Pesquisar");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(pesquisar);
        pesquisar.setBounds(40, 190, 100, 29);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Núm:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(360, 100, 50, 17);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.empresa.nomefantasia}"), fantasia, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.editar}"), fantasia, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);

        getContentPane().add(fantasia);
        fantasia.setBounds(410, 40, 250, 27);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Incs. Estadual:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 70, 100, 17);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.empresa.email}"), email, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.editar}"), email, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);

        getContentPane().add(email);
        email.setBounds(410, 130, 250, 27);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Endereço:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 100, 70, 17);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.empresa.numero}"), num, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.editar}"), num, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);

        getContentPane().add(num);
        num.setBounds(410, 100, 70, 27);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Telefone:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 130, 70, 17);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.empresa.telefone}"), telefone, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.editar}"), telefone, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);

        getContentPane().add(telefone);
        telefone.setBounds(90, 130, 100, 27);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Contato:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(190, 130, 70, 17);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.empresa.contato}"), contato, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.editar}"), contato, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);

        getContentPane().add(contato);
        contato.setBounds(260, 130, 90, 27);

        labelPatr.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPatr.setText("Patrocinador:");
        getContentPane().add(labelPatr);
        labelPatr.setBounds(0, 160, 90, 17);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.editar}"), patrocinador, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);

        getContentPane().add(patrocinador);
        patrocinador.setBounds(90, 160, 260, 27);

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar);
        cancelar.setBounds(300, 190, 90, 29);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${empresas.listaEmpresa}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tabelaEmpresas);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idempresa}"));
        columnBinding.setColumnName("Código");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cnpj}"));
        columnBinding.setColumnName("CNPJ");
        columnBinding.setColumnClass(Long.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nomefantasia}"));
        columnBinding.setColumnName("Empresa");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.empresa}"), tabelaEmpresas, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(tabelaEmpresas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 230, 690, 200);

        selecionar.setText("Selecionar");
        selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarActionPerformed(evt);
            }
        });
        getContentPane().add(selecionar);
        selecionar.setBounds(10, 430, 110, 29);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("E-mail:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(340, 130, 70, 17);

        excluir.setText("Excluir");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${not empty empresas.empresa.idempresa}"), excluir, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });
        getContentPane().add(excluir);
        excluir.setBounds(490, 190, 90, 29);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.empresa.cnpj}"), cnpj, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${empresas.editar}"), cnpj, org.jdesktop.beansbinding.BeanProperty.create("editable"));
        bindingGroup.addBinding(binding);

        getContentPane().add(cnpj);
        cnpj.setBounds(90, 70, 180, 27);

        getAccessibleContext().setAccessibleName("Cadastro/Manutenção de Empresa");

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        try {
            if (empresas.getEmpresa() == null) {
                String validacao = validaEmpresa();
                if (validacao.isEmpty()) {

                    List<Empresa> lista = new EmpresaFacade().pesquisarEmpresa(null, razaoSocial.getText(), fantasia.getText(),
                            cnpj.getText(), insEstadual.getText(), null, num.getText(), null,
                            null, contato.getText(), email.getText(), patrocinador.getText());
                    if (lista.isEmpty()) {
                        Empresa nova = new Empresa();
                        nova.setRazaosocial(razaoSocial.getText());
                        nova.setCnpj(cnpj.getText().isEmpty() ? 0l : new Long(cnpj.getText()));
                        nova.setComplemento(complemento.getText());
                        nova.setContato(contato.getText());
                        nova.setEmail(email.getText());
                        nova.setEndereco(endereco.getText());
                        if (!insEstadual.getText().isEmpty()) {
                            nova.setInscricaoestadual(new BigInteger(insEstadual.getText()));
                        }
                        nova.setNomefantasia(fantasia.getText());
                        nova.setNumero(num.getText().isEmpty() ? 0 : new Integer(num.getText()));
                        nova.setPatrocinador(patrocinador.getText());
                        nova.setTelefone(telefone.getText());
                        nova.setAtivoList(new ArrayList<Ativo>());
                        Ativo ativo = new Ativo(null, "ORGANIZACIONAL", "ORGANIZACIONAL");
                        ativo.setIdempresa(nova);
                        nova.getAtivoList().add(ativo);
                        new EmpresaFacade().salvarEmpresa(nova);
                        Funcoes.info("Empresa", nova.getRazaosocial() + " cadastrada com sucesso.");
                        empresas.getListaEmpresa().add(nova);
                        empresas.setEmpresa(nova);
                        habilita();
                    } else {
                        Funcoes.warn("Empresa", "Empresa já cadastrada.");
                    }
                } else {
                    Funcoes.warn("Empresa", "Por favor, preencha o campo '" + validacao + "'.");
                }
            } else if (empresas.getEmpresa().getRazaosocial().isEmpty()) {
                Funcoes.warn("Razão Social", "Preencha a razão social da empresa.");
            } else {
                Empresa emp = empresas.getEmpresa();
                new EmpresaFacade().salvarAtualizarEmpresa(emp);
                empresas.setEmpresa(emp);
                for (int x = 0; x < empresas.getListaEmpresa().size(); x++) {
                    if (empresas.getListaEmpresa().get(x).getIdempresa().equals(emp.getIdempresa())) {
                        empresas.getListaEmpresa().set(x, emp);
                        break;
                    }
                }
                Funcoes.info("Empresa", emp.getRazaosocial() + " cadastrada com sucesso.");
                habilita();
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            Funcoes.erro("Salvar", ex.getMessage());
        }


    }//GEN-LAST:event_salvarActionPerformed

    private void novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoActionPerformed

        try {
            tabelaEmpresas.clearSelection();

            empresas.novaEmpresa();
            insEstadual.setText("");
            num.setText("");
            cnpj.setText("");
            tabelaEmpresas.setEnabled(false);
            idEmpresa.setEnabled(false);
            salvar.setEnabled(true);
            pesquisar.setEnabled(false);
            cancelar.setEnabled(true);
            alterar.setEnabled(false);
            this.revalidate();
            this.repaint();
        } catch (Exception ex) {
            ex.printStackTrace();
            Funcoes.erro("Erro", ex.getMessage());
        }

    }//GEN-LAST:event_novoActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        if (depende) {
            dialog.dispose();
        } else {
            this.dispose();
        }
    }//GEN-LAST:event_sairActionPerformed

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
        try {
            EmpresaFacade facade = new EmpresaFacade();
            empresas.getListaEmpresa().clear();
            List<Empresa> lista = new ArrayList<Empresa>();
            //Map<String, Object> map = pesquisarParametros();
            lista = facade.pesquisarEmpresa(idEmpresa.getText(), razaoSocial.getText(), fantasia.getText(),
                    cnpj.getText(), insEstadual.getText(), endereco.getText(), num.getText(), complemento.getText(),
                    telefone.getText(), contato.getText(), email.getText(), patrocinador.getText());
            empresas.setListaEmpresa(lista);
            for (Empresa e : empresas.getListaEmpresa()) {
                for (Ativo p : e.getAtivoList()) {
                    p.getIdempresa();
                }
            }
            int size = empresas.getListaEmpresa().size();
            if (empresas.getListaEmpresa().isEmpty()) {
                alterar.setEnabled(false);
            } else {
                alterar.setEnabled(true);
            }
        } catch (Exception ex) {
            Funcoes.erro("Pesquisa", ex.getMessage());
        }
    }//GEN-LAST:event_pesquisarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        novo.setEnabled(true);
        novo.setEnabled(true);
        pesquisar.setEnabled(true);
        salvar.setEnabled(false);
        cancelar.setEnabled(false);
        alterar.setEnabled(true);
        idEmpresa.setText("");
        idEmpresa.setEnabled(true);
        tabelaEmpresas.setEnabled(true);
        empresas.setEditar(false);
        empresas.setEmpresa(new Empresa());
        tabelaEmpresas.clearSelection();
    }//GEN-LAST:event_cancelarActionPerformed

    private void selecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarActionPerformed
        dialog.setVisible(false);
        empresas.getEmpresa();
    }//GEN-LAST:event_selecionarActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
        if (empresas.getEmpresa() != null) {
            novo.setEnabled(false);
            pesquisar.setEnabled(false);
            salvar.setEnabled(true);
            cancelar.setEnabled(true);
            alterar.setEnabled(false);
            tabelaEmpresas.setEnabled(false);
            empresas.setEditar(true);
            idEmpresa.setEditable(false);
        } else {
            Funcoes.warn("Empresa", "Selecione uma empresa.");
        }
    }//GEN-LAST:event_alterarActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        try {
            if (empresas.getEmpresa() == null) {
                Funcoes.erro("Empresa", "Selecione uma empresa.");
            } else {
                int opcao = Funcoes.opcao("Excluir", "Deseja excluir a empresa " + empresas.getEmpresa().getRazaosocial() + "?");
                if (opcao == 0) {
                    new EmpresaFacade().excluirEmpresa(empresas.getEmpresa());
                    List<Empresa> lista = empresas.getListaEmpresa();
                    lista.remove(empresas.getEmpresa());
                    empresas.setEmpresa(null);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            Funcoes.erro("Erro", e.getMessage());
        }
    }//GEN-LAST:event_excluirActionPerformed

    public Empresa getEmpresaSelecionada() {
        return empresas.getEmpresa();
    }

    public ModeloEmpresa getEmpresas() {
        return empresas;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JButton cancelar;
    private javax.swing.JFormattedTextField cnpj;
    private javax.swing.JTextField complemento;
    private javax.swing.JTextField contato;
    private javax.swing.JTextField email;
    private javax.swing.JTextField endereco;
    private javax.swing.JButton excluir;
    private javax.swing.JTextField fantasia;
    private javax.swing.JTextField idEmpresa;
    private javax.swing.JTextField insEstadual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPatr;
    private javax.swing.JButton novo;
    private javax.swing.JTextField num;
    private javax.swing.JTextField patrocinador;
    private javax.swing.JButton pesquisar;
    private javax.swing.JTextField razaoSocial;
    private javax.swing.JButton sair;
    private javax.swing.JButton salvar;
    private javax.swing.JButton selecionar;
    private javax.swing.JTable tabelaEmpresas;
    private javax.swing.JTextField telefone;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private ModeloEmpresa empresas;
    private boolean depende = false;
    private JDialog dialog;

    private String validaEmpresa() {
        String valida = "";
        if (fantasia.getText().isEmpty()) {
            valida = "Nome Fantasia";
        } else if (patrocinador.getText().isEmpty()) {
            valida = "Patrocinador";
        } else if (contato.getText().isEmpty()) {
            valida = "Contato";
        } else if (email.getText().isEmpty()) {
            valida = "Email";
        }
        return valida;

    }
}
