/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaAtivo.java
 *
 * Created on 29/09/2009, 21:07:50
 */
package appcmmi.form.empresa;

import appcmmi.PrincipalFrame;
import appcmmi.db.facade.EmpresaFacade;
import appcmmi.db.facade.modelo.AtivoFacade;
import appcmmi.db.pojo.Empresa;
import appcmmi.db.pojo.Ativo;
import appcmmi.funcoes.Funcoes;
import appcmmi.modelo.bind.ModeloAtivo;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.List;
import javax.swing.JDialog;

/**
 *
 * @author Alexandre
 */
public class TelaAtivo extends javax.swing.JInternalFrame {

    /** Creates new form TelaAtivo */
    public TelaAtivo() {
        inicial();
    }

    public TelaAtivo(JDialog dialog, Empresa empresa, boolean depende) {
        this.dialog = dialog;
        this.depende = depende;
        inicial();
        model.setEmpresa(empresa);
    }

    private void inicial() {
        model = new ModeloAtivo();
        initComponents();
        this.setSize(700, 450);
        selecionar.setVisible(depende);
        selecionar.setEnabled(depende);

        jButton1.addFocusListener(new FocusListener() {

            @Override
            public void focusGained(FocusEvent arg0) {
            }

            @Override
            public void focusLost(FocusEvent arg0) {
                try {
                    if (!idEmpresa.getText().isEmpty()) {
                        Empresa procurada = new EmpresaFacade().carregarEmpresa(new Integer(idEmpresa.getText()));
                        model.setEmpresa(procurada);
                    }
                } catch (Exception ex) {
                    ex.printStackTrace();
                    Funcoes.erro("Erro", ex.getMessage());
                }
            }
        });
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEventos = new javax.swing.JTable();
        incluir = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        Ativo = new javax.swing.JLabel();
        nomeEvento = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idEmpresa = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        selecionar = new javax.swing.JButton();
        lbldesc = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(true);
        setTitle("Cadastro de Ativos");
        getContentPane().setLayout(null);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${model.listaAtivo}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tabelaEventos);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${descricao}"));
        columnBinding.setColumnName("Descricao");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.projeto}"), tabelaEventos, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.selecionados}"), tabelaEventos, org.jdesktop.beansbinding.BeanProperty.create("selectedElements"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${not empty model.empresa}"), tabelaEventos, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(tabelaEventos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 240, 620, 110);

        incluir.setText("Incluir");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${not empty model.empresa}"), incluir, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incluirActionPerformed(evt);
            }
        });
        getContentPane().add(incluir);
        incluir.setBounds(80, 210, 100, 29);

        excluir.setText("Excluir");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${not empty model.empresa}"), excluir, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });
        getContentPane().add(excluir);
        excluir.setBounds(190, 210, 110, 29);

        sair.setText("Fechar");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair);
        sair.setBounds(460, 360, 80, 29);

        Ativo.setText("Evento");
        getContentPane().add(Ativo);
        Ativo.setBounds(20, 70, 60, 17);
        getContentPane().add(nomeEvento);
        nomeEvento.setBounds(80, 70, 450, 27);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Empresa"));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Código:");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.empresa.idempresa}"), idEmpresa, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        nome.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${model.empresa.razaosocial}"), nome, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Nome:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appcmmi/form/imagem/lupa.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(idEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 640, 60);

        selecionar.setText("Selecionar");
        selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarActionPerformed(evt);
            }
        });
        getContentPane().add(selecionar);
        selecionar.setBounds(30, 360, 100, 29);

        lbldesc.setText("Descrição");
        getContentPane().add(lbldesc);
        lbldesc.setBounds(0, 110, 70, 17);

        descricao.setColumns(20);
        descricao.setRows(5);
        jScrollPane2.setViewportView(descricao);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(80, 110, 450, 87);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incluirActionPerformed
        try {
            AtivoFacade facade = new AtivoFacade();
            if (nomeEvento.getText().isEmpty()) {
                Funcoes.warn("Ativo", "Preencha o campo 'Nome'");
            } else if (!facade.confereAtivo(nomeEvento.getText())) {
                Funcoes.warn("Ativo", "Ativo já cadastrado");
            } else {
                Ativo novo = new Ativo();
                novo.setNome(nomeEvento.getText());
                novo.setDescricao(descricao.getText());
                novo.setIdempresa(model.getEmpresa());
                List<Ativo> lista = model.getListaAtivo();
                lista.add(novo);
                model.getEmpresa().setAtivoList(lista);
                model.setListaAtivo(lista);
                //new EmpresaFacade().salvarEmpresa(model.getEmpresa());
                facade.salvarAtivo(novo);
                nomeEvento.setText("");
                descricao.setText("");
                nomeEvento.requestFocus();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            Funcoes.erro("Erro", ex.getMessage());
        }
}//GEN-LAST:event_incluirActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        try {
            Empresa empresa = model.getEmpresa();
            empresa.setAtivoList(model.getListaAtivo());
            new EmpresaFacade().salvarAtualizarEmpresa(empresa);
            if (depende) {
                dialog.dispose();
            } else {
                this.dispose();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            Funcoes.erro("Ativo", ex.getMessage());
        }
    }//GEN-LAST:event_sairActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JDialog d = new JDialog(PrincipalFrame.getFrames()[0], true);
        TelaEmpresa empresa = new TelaEmpresa(d);
        d.setLocation(empresa.getLocation().x + 30, empresa.getLocation().y + 30);
        d.add(empresa);
        d.setSize(empresa.getSize());
        d.setVisible(true);
        model.setEmpresa(empresa.getEmpresaSelecionada());
        d.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        try {
            if (model.getProjeto() != null) {
                int opcao = Funcoes.opcao("Exclusão", "Deseja excluir o ativo " + model.getProjeto().getNome() + "?");
                if (opcao == 0) {
                    Ativo apaga = model.getProjeto();
                    List<Ativo> lista = model.getListaAtivo();
                    lista.remove(apaga);
                    model.getEmpresa().getAtivoList().remove(apaga);
                    model.setListaAtivo(lista);
                    new AtivoFacade().excluirAtivo(apaga);
                }
            } else {
                Funcoes.erro("Ativo", "Selecione um ativo");
            }
        } catch (Exception e) {
            Funcoes.erro("Erro", e.getMessage());
        }
        model.excluirProjeto();
    }//GEN-LAST:event_excluirActionPerformed

    private void selecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarActionPerformed
        if (dialog != null) {
            dialog.dispose();
        }
    }//GEN-LAST:event_selecionarActionPerformed

    public ModeloAtivo getModel() {
        return this.model;
    }

    public List<Ativo> getSelecionados() {
        return model.getSelecionados();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ativo;
    private javax.swing.JTextArea descricao;
    private javax.swing.JButton excluir;
    private javax.swing.JTextField idEmpresa;
    private javax.swing.JButton incluir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbldesc;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField nomeEvento;
    private javax.swing.JButton sair;
    private javax.swing.JButton selecionar;
    private javax.swing.JTable tabelaEventos;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    private ModeloAtivo model;
    private boolean depende;
    private JDialog dialog;
}
