/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaPropriedades.java
 *
 * Created on 27/10/2009, 20:57:05
 */
package appcmmi.form.login;

import appcmmi.funcoes.Propriedades;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 * Tela de alteração de propriedades do banco de dados
 * @author diego
 */
public class TelaPropriedades extends javax.swing.JDialog {

    /** Creates new form TelaPropriedades */
    public TelaPropriedades(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String url = Propriedades.getPreferences().get(Propriedades.URL_BD, "");
        if (!url.isEmpty()) {
            seleciona.setSelectedFile(new File(url));
        }
        this.setSize(450, 450);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleciona = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Propriedades");
        getContentPane().setLayout(null);

        seleciona.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        seleciona.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionaActionPerformed(evt);
            }
        });
        getContentPane().add(seleciona);
        seleciona.setBounds(0, 0, 435, 415);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Salva o diretório selecionado nas preferências da aplicação.
     * @author diego
     * @param evt
     */
    private void selecionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionaActionPerformed
        try {
            if (evt.getActionCommand().equals("ApproveSelection")) {
                StringBuffer path = new StringBuffer(seleciona.getSelectedFile().getPath());
                path.append("/cmmi;");
                Propriedades.getPreferences().put(Propriedades.URL_BD, path.toString());
                Propriedades.getPreferences().sync();
                Propriedades.getPreferences().flush();
            }
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(TelaPropriedades.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro", ex.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                TelaPropriedades dialog = new TelaPropriedades(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser seleciona;
    // End of variables declaration//GEN-END:variables
}
